dist: trusty
language: node_js
branches:
  only:
  - master
cache:
  directories:
    - node_modules
env:
  global:
  - NVS_VERSION=1.5.2
  matrix:
  - NODEJS_VERSION=node/8
  - NODEJS_VERSION=node/10
  - NODEJS_VERSION=node/12
before_install:
# Install NVS.
- git clone --branch v$NVS_VERSION --depth 1 https://github.com/jasongin/nvs ~/.nvs
- . ~/.nvs/nvs.sh
- nvs --version
install:
# Install the selected version of Node.js using NVS.
- nvs add $NODEJS_VERSION
- nvs use $NODEJS_VERSION
- node --version
- npm --version
# Install the application's NPM dependencies.
- npm install
script:
- npm run build
- npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
    condition: $NODEJS_VERSION = node/10
